### PR TITLE
Release

### PR DESCRIPTION
**Pull request by alexandru5**
Please review my code for pull request

### CODE REVIEW

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]
"No input validation"

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]

**Review by RobertDG11 — APPROVED** [review]

**Review by Dragos800 — APPROVED** [review]
Frumoasa clasa main, foarte clean
Interesanta ideea cu Session 
Foarte folositoare comentariile

**Review by juga3 — APPROVED** [review]
Nicely done, b0$$

**Review by mariusola — APPROVED** [review]
-clean code
-comentarii explicite
-10/10

**Pull request merged**
